---
- name: Deploy Tomcat Container
  hosts: localhost
  task:
    - name: create container
      docker_container:
        name: webserver 
        image: tomcat:hello
        state: started
        port: 
          - "80:8080"
... 
