---
- name: Deploy Tomcat Container
  hosts: localhost
  tasks:
  - name: create container
    docker_container:
      name: webserver 
      image: tomcat:hello
      state: started
      ports: 
        - "81:8080"
... 
